FROM ghcr.io/php/pie:bin@sha256:c337dc8e757c609e4cb454df04c7b733a7d3aaf0f5ee49fc76f9828691fe6342 AS pie-installer

FROM php:8.1.34-fpm@sha256:a3118db1911fdd3b3ac66605122ddc859286688ced86fc860fec6d19cc2d6c55

RUN apt update
RUN apt install -y zlib1g-dev g++ libicu-dev libzip-dev zip libpq-dev libxml2-dev libcurl4-openssl-dev libonig-dev
RUN docker-php-ext-install intl xml curl mbstring opcache mysqli pdo pdo_mysql sockets zip bcmath
RUN docker-php-ext-configure zip

# Install dependencies for GD and install GD with support for jpeg, png webp and freetype
RUN apt install -y libjpeg-dev libpng-dev libwebp-dev libfreetype6-dev

RUN docker-php-ext-configure gd --with-jpeg --with-webp --with-freetype
RUN docker-php-ext-install gd

# Install Redis Dependency
# renovate: datasource=github-tags depName=igbinary/igbinary  versioning=semver
ENV PHP_IGBINARY_VERSION="3.2.17RC1"

RUN --mount=type=bind,from=pie-installer,source=/pie,target=/usr/local/bin/pie \
    pie install igbinary/igbinary:${PHP_IGBINARY_VERSION}

# Install Redis
# renovate: datasource=github-tags depName=phpredis/phpredis versioning=semver
ENV PHP_REDIS_VERSION="6.3.0"

RUN --mount=type=bind,from=pie-installer,source=/pie,target=/usr/local/bin/pie \
    pie install phpredis/phpredis:${PHP_REDIS_VERSION}

# Install APCu
# renovate: datasource=github-tags depName=krakjoe/apcu versioning=semver
ENV PHP_APCU_VERSION="v5.1.28"

RUN --mount=type=bind,from=pie-installer,source=/pie,target=/usr/local/bin/pie \
    pie install apcu/apcu:${PHP_APCU_VERSION}

# Cleanup a bit
RUN rm -r /var/lib/apt/lists/*

EXPOSE 9000
CMD ["php-fpm"]
