FROM php:8.4.8-fpm@sha256:bde9f38a461e8f9bbc9d1894fee6254fabea1a373c2d638ee0d26446240094c8

RUN pecl channel-update pecl.php.net

RUN apt update
RUN apt install -y zlib1g-dev g++ libicu-dev libzip-dev zip libpq-dev libxml2-dev libcurl4-openssl-dev libonig-dev libc-client-dev libkrb5-dev
RUN docker-php-ext-install intl xml curl mbstring opcache mysqli pdo pdo_mysql sockets zip bcmath
RUN docker-php-ext-configure zip

RUN pecl install imap && \
    docker-php-ext-enable imap

# Install dependencies for GD and install GD with support for jpeg, png webp and freetype
RUN apt install -y libjpeg-dev libpng-dev libwebp-dev libfreetype6-dev

RUN docker-php-ext-configure gd --with-jpeg --with-webp --with-freetype
RUN docker-php-ext-install gd

# Install Redis Dependency
# renovate: datasource=github-tags depName=igbinary/igbinary versioning=semver
ENV PHP_IGBINARY_VERSION="3.2.16"

RUN pecl install igbinary-${PHP_IGBINARY_VERSION}
RUN docker-php-ext-enable igbinary

# Install Redis
# renovate: datasource=github-tags depName=phpredis/phpredis versioning=semver
ENV PHP_REDIS_VERSION="6.2.0"

RUN pecl install redis-${PHP_REDIS_VERSION}
RUN docker-php-ext-enable redis

# Install APCu
# renovate: datasource=github-tags depName=krakjoe/apcu versioning=semver
ENV PHP_APCU_VERSION="v5.1.24"

RUN pecl install apcu-${PHP_APCU_VERSION#"v"}
RUN docker-php-ext-enable apcu

RUN echo pecl info apcu

EXPOSE 9000
CMD ["php-fpm"]