FROM ghcr.io/php/pie:bin@sha256:24df295bb3dbf6cbcb42f49a14eaef043b99ccaa17f8412f3c04eb330e6da12d AS pie-installer

FROM php:8.3.30-fpm@sha256:6754d4da4545f912c55671e4dd2eb79ea4d1ed677b93e1c5415fe46d1a46b23d

RUN apt update
RUN apt install -y zlib1g-dev g++ libicu-dev libzip-dev zip libpq-dev libxml2-dev libcurl4-openssl-dev libonig-dev
RUN docker-php-ext-install intl xml curl mbstring opcache mysqli pdo pdo_mysql sockets zip bcmath
RUN docker-php-ext-configure zip

# Install dependencies for GD and install GD with support for jpeg, png webp and freetype
RUN apt install -y libjpeg-dev libpng-dev libwebp-dev libfreetype6-dev

RUN docker-php-ext-configure gd --with-jpeg --with-webp --with-freetype
RUN docker-php-ext-install gd

# Install Redis Dependency
# renovate: datasource=github-tags depName=igbinary/igbinary  versioning=semver
ENV PHP_IGBINARY_VERSION="3.2.17RC1"

RUN --mount=type=bind,from=pie-installer,source=/pie,target=/usr/local/bin/pie \
    pie install igbinary/igbinary:${PHP_IGBINARY_VERSION}

# Install Redis
# renovate: datasource=github-tags depName=phpredis/phpredis versioning=semver
ENV PHP_REDIS_VERSION="6.3.0"

RUN --mount=type=bind,from=pie-installer,source=/pie,target=/usr/local/bin/pie \
    pie install phpredis/phpredis:${PHP_REDIS_VERSION}

# Install APCu
# renovate: datasource=github-tags depName=apcu/apcu versioning=semver
ENV PHP_APCU_VERSION="v5.1.28"

RUN --mount=type=bind,from=pie-installer,source=/pie,target=/usr/local/bin/pie \
    pie install apcu/apcu:${PHP_APCU_VERSION}

EXPOSE 9000
CMD ["php-fpm"]
