FROM ghcr.io/php/pie:bin@sha256:9fb4fb481767c48f7c57a7fc2c1ccef6ec8fc1e254751a77213cfb0c8f181eba AS pie-installer

FROM php:8.4.23-fpm@sha256:3661dc717d73bdb0ec58bcdc96af36af90f8894c66c09ac74721a012b01da6f4

RUN apt update
RUN apt install -y zlib1g-dev g++ libicu-dev libzip-dev zip libpq-dev libxml2-dev libcurl4-openssl-dev libonig-dev
RUN docker-php-ext-install intl xml curl mbstring opcache mysqli pdo pdo_mysql sockets zip bcmath
RUN docker-php-ext-configure zip

# Install dependencies for GD and install GD with support for jpeg, png webp and freetype
RUN apt install -y libjpeg-dev libpng-dev libwebp-dev libfreetype6-dev

RUN docker-php-ext-configure gd --with-jpeg --with-webp --with-freetype
RUN docker-php-ext-install gd

# Install Redis Dependency
# renovate: datasource=github-tags depName=igbinary/igbinary  versioning=semver
ENV PHP_IGBINARY_VERSION="3.2.17RC1"

RUN --mount=type=bind,from=pie-installer,source=/pie,target=/usr/local/bin/pie \
    pie install igbinary/igbinary:${PHP_IGBINARY_VERSION}

# Install Redis
# renovate: datasource=github-tags depName=phpredis/phpredis versioning=semver
ENV PHP_REDIS_VERSION="6.3.0"

RUN --mount=type=bind,from=pie-installer,source=/pie,target=/usr/local/bin/pie \
    pie install phpredis/phpredis:${PHP_REDIS_VERSION}

# Install APCu
# renovate: datasource=github-tags depName=krakjoe/apcu versioning=semver
ENV PHP_APCU_VERSION="v5.1.28"

RUN --mount=type=bind,from=pie-installer,source=/pie,target=/usr/local/bin/pie \
    pie install apcu/apcu:${PHP_APCU_VERSION}

EXPOSE 9000
CMD ["php-fpm"]
