name: Docker image build test

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  merge_group:
  push:
    branches:
      - 'renovate/**'

# Prevent duplicates for PRs, but allow main/merge_group to finish to warm caches
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  docker:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - docker-file: "./Dockerfile.php.8.1"
            image-tag-suffix: "-php8.1"
          - docker-file: "./Dockerfile.php.8.2"
            image-tag-suffix: "-php8.2"
          - docker-file: "./Dockerfile.php.8.3"
            image-tag-suffix: "-php8.3"
          - docker-file: "./Dockerfile.php.8.4"
            image-tag-suffix: "-php8.4"

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3

      - name: Login to ghcr
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (test) with cached layers
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ${{ matrix.docker-file }}
          platforms: linux/amd64
          load: true
          tags: ghcr.io/sgoettsch/docker-php-fpm:latest${{ matrix.image-tag-suffix }}

          # Import caches: branch-specific, main, and optional registry cache
          cache-from: |
            type=gha,scope=${{ github.workflow }}-${{ matrix.image-tag-suffix }}-${{ github.ref_name }}
            type=gha,scope=${{ github.workflow }}-${{ matrix.image-tag-suffix }}-main
            type=registry,ref=ghcr.io/sgoettsch/docker-php-fpm:cache${{ matrix.image-tag-suffix }}

          # Export cache back to branch-specific scope
          cache-to: |
            type=gha,mode=max,scope=${{ github.workflow }}-${{ matrix.image-tag-suffix }}-${{ github.ref_name }}

      - name: Smoke test
        run: |
          docker run --rm ghcr.io/sgoettsch/docker-php-fpm:latest${{ matrix.image-tag-suffix }} php -v
